# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""FFI API."""

from typing import Any

def ModuleGetKind(*args: Any) -> Any: ...
def ModuleImplementsFunction(*args: Any) -> Any: ...
def ModuleGetFunction(*args: Any) -> Any: ...
def ModuleImportModule(*args: Any) -> Any: ...
def ModuleInspectSource(*args: Any) -> Any: ...
def ModuleGetWriteFormats(*args: Any) -> Any: ...
def ModuleGetPropertyMask(*args: Any) -> Any: ...
def ModuleClearImports(*args: Any) -> Any: ...
def ModuleWriteToFile(*args: Any) -> Any: ...
def ModuleLoadFromFile(*args: Any) -> Any: ...
def SystemLib(*args: Any) -> Any: ...
def Array(*args: Any) -> Any: ...
def ArrayGetItem(*args: Any) -> Any: ...
def ArraySize(*args: Any) -> Any: ...
def MapForwardIterFunctor(*args: Any) -> Any: ...
def Map(*args: Any) -> Any: ...
def MapGetItem(*args: Any) -> Any: ...
def MapCount(*args: Any) -> Any: ...
def MapSize(*args: Any) -> Any: ...
def MakeObjectFromPackedArgs(*args: Any) -> Any: ...
def ToJSONGraphString(*args: Any) -> Any: ...
def FromJSONGraphString(*args: Any) -> Any: ...
def Shape(*args: Any) -> Any: ...
